-- ========================================================
-- SRI DURGAA CLINICAL LABORATORY (PONNERI)
-- Initial Seed Data
-- Database: clinic
-- ========================================================

-- Seed Diagnostic Tests
INSERT INTO tests (
    id, title, title_ta, category, category_ta, image,
    description, description_ta, parameters, parameters_ta,
    preparation, preparation_ta, sample_type, sample_type_ta,
    turnaround, turnaround_ta, guidelines, guidelines_ta,
    meta1, meta1_ta, meta2, meta2_ta, icon_type, price
) VALUES
(
    'cbc',
    'CBC – Complete Blood Count',
    'CBC – முழு இரத்த அணுக்கள் பரிசோதனை',
    'Blood & Pathology',
    'இரத்தம் & நோயியல்',
    '/assets/images/tests/test-cbc-mindray.png',
    'Evaluates overall health and detects a wide variety of disorders, including anemia, infection, inflammation, bleeding disorders, and leukemia.',
    'இரத்த சோகை, நோய்த்தொற்று, உடல் வீக்கம், இரத்த உறைதல் கோளாறுகள் மற்றும் இரத்தப் புற்றுநோய் உள்ளிட்ட பல்வேறு உடல்நலக் குறைபாடுகளைத் துல்லியமாக அறியும் முதன்மைப் பரிசோதனை.',
    '["Hemoglobin (Hb)", "Total RBC Count", "Total WBC (Leukocyte) Count", "Differential Count (Neutrophils, Lymphocytes, Monocytes, Eosinophils, Basophils)", "Platelet Count", "PCV / Hematocrit", "MCV, MCH, MCHC, RDW"]'::jsonb,
    '["ஹீமோகுளோபின் (Hb)", "மொத்த RBC எண்ணிக்கை", "மொத்த வெள்ளை இரத்த அணுக்கள் (WBC)", "வேறுபட்ட அணுக்கள் (நியூட்ரோபில், லிம்போசைட், மோனோசைட், ஈசினோபில், பாசோபில்)", "பிளேட்லெட் எண்ணிக்கை", "PCV / ஹெமடோக்ரிட்", "MCV, MCH, MCHC, RDW"]'::jsonb,
    'No special fasting required. Stay normally hydrated.',
    'சிறப்பு உணவுக் கட்டுப்பாடு தேவையில்லை. வழக்கம்போல் நீர் அருந்தலாம்.',
    '2 ml Whole Blood in EDTA tube',
    '2 மிலி முழு இரத்தம் (EDTA குப்பி)',
    '4 to 6 Hours (Same Day Delivery)',
    '4 முதல் 6 மணி நேரம் (அன்றே அறிக்கை)',
    'Crucial baseline screening recommended as part of routine health evaluation or pre-operative assessments.',
    'வழக்கமான உடல்நலப் பரிசோதனை மற்றும் அறுவை சிகிச்சைக்கு முந்தைய மதிப்பீட்டிற்கு மிகவும் அவசியம்.',
    'Turnaround: 4-6 Hours',
    'முடிவு வழங்கும் நேரம்: 4-6 மணி நேரம்',
    'Fasting: No',
    'வெறும் வயிறு: தேவையில்லை',
    'blood',
    250.00
),
(
    'kft',
    'KFT – Kidney Function Test (Renal Profile)',
    'KFT – சிறுநீரக செயல்பாட்டு பரிசோதனை (Renal Profile)',
    'Organ Profiles',
    'உறுப்பு செயல்பாட்டுப் பரிசோதனைகள்',
    '/assets/images/tests/test-kft-bench.png',
    'Assesses how effectively your kidneys are filtering metabolic waste and balancing fluids and minerals.',
    'சிறுநீரகங்கள் இரத்தத்தில் உள்ள கழிவுகளை எந்த அளவுக்குச் சரியாக வடிகட்டுகின்றன மற்றும் உடலின் தாது உப்புகளைச் சமநிலைப்படுத்துகின்றன என்பதை மதிப்பிடுகிறது.',
    '["Blood Urea & BUN", "Serum Creatinine", "Uric Acid", "Serum Electrolytes (Sodium, Potassium, Chloride)", "Estimated GFR (eGFR)", "Blood Urea Nitrogen / Creatinine Ratio"]'::jsonb,
    '["இரத்த யூரியா & BUN", "சீரம் கிரியேட்டினின்", "யூரிக் அமிலம்", "சீரம் எலக்ட்ரோலைட்டுகள் (சோடியம், பொட்டாசியம், குளோரைடு)", "மதிப்பிடப்பட்ட GFR (eGFR)", "யூரியா / கிரியேட்டினின் விகிதம்"]'::jsonb,
    '8 to 10 hours overnight fasting recommended. Avoid heavy meat intake 24h prior.',
    'இரவு முழுவதும் 8 முதல் 10 மணி நேரம் வெறும் வயிற்றில் இருப்பது பரிந்துரைக்கப்படுகிறது.',
    '3 ml Venous Blood (Clot Activator / Serum)',
    '3 மிலி சிரை இரத்தம் (சீரம்)',
    'Same Day Evening',
    'அன்றே மாலை அறிக்கை',
    'Essential for patients with hypertension, diabetes, swelling, or long-term medication monitoring.',
    'உயர் இரத்த அழுத்தம், சர்க்கரை நோய், உடல் வீக்கம் உள்ளவர்களுக்கும் மருந்து உண்பவர்களுக்கும் அவசியம்.',
    'Same Day Report',
    'அன்றே அறிக்கை வழங்கப்படும்',
    'Fasting: 8-10 Hrs',
    'வெறும் வயிறு: 8-10 மணி நேரம்',
    'organ',
    650.00
),
(
    'lft',
    'LFT – Liver Function Test (Hepatic Profile)',
    'LFT – கல்லீரல் செயல்பாட்டு பரிசோதனை (Hepatic Profile)',
    'Organ Profiles',
    'உறுப்பு செயல்பாட்டுப் பரிசோதனைகள்',
    '/assets/images/tests/test-lft-erba.png',
    'Comprehensive diagnostic panel measuring enzymes, proteins, and bilirubin produced or cleared by the liver.',
    'கல்லீரலால் உற்பத்தி செய்யப்படும் என்சைம்கள், புரதங்கள் மற்றும் பிலிரூபின் அளவுகளைக் கணக்கிட்டு கல்லீரலின் இயக்கத்தை விரிவாக அறியும் பரிசோதனை.',
    '["Total, Direct & Indirect Bilirubin", "SGOT / AST (Aspartate Aminotransferase)", "SGPT / ALT (Alanine Aminotransferase)", "Alkaline Phosphatase (ALP)", "Total Protein & Albumin / Globulin (A/G) Ratio", "Gamma GT (GGT)"]'::jsonb,
    '["மொத்த & நேரடி பிலிரூபின்", "SGOT / AST", "SGPT / ALT", "ஆல்கலைன் பாஸ்பேடேஸ் (ALP)", "மொத்த புரதம் & அல்புமின்/குளோபுலின் விகிதம்", "காமா GT (GGT)"]'::jsonb,
    '10 to 12 hours overnight fasting required. Abstain from alcohol for 48 hours prior.',
    '10 முதல் 12 மணி நேரம் வெறும் வயிறு தேவை. 48 மணி நேரத்திற்கு முன் மது அருந்தக் கூடாது.',
    '3 ml Venous Blood (Clot Activator / Serum)',
    '3 மிலி சிரை இரத்தம் (சீரம்)',
    'Same Day Evening',
    'அன்றே மாலை அறிக்கை',
    'Identifies early liver inflammation, viral hepatitis, fatty liver, jaundice, and drug-induced hepatotoxicity.',
    'மஞ்சள் காமாலை, கொழுப்பு கல்லீரல் (Fatty Liver) மற்றும் கல்லீரல் பாதிப்புகளைக் கண்டறிய உதவும்.',
    'Same Day Report',
    'அன்றே அறிக்கை வழங்கப்படும்',
    'Fasting: 10-12 Hrs',
    'வெறும் வயிறு: 10-12 மணி நேரம்',
    'liver',
    600.00
),
(
    'lipid',
    'Lipid Profile (Cholesterol & Cardiac Risk Panel)',
    'Lipid Profile – கொலஸ்ட்ரால் / கொழுப்பு பரிசோதனை',
    'Organ Profiles',
    'உறுப்பு செயல்பாட்டுப் பரிசோதனைகள்',
    '/assets/images/tests/test-lipid-tubes.png',
    'Complete quantitative evaluation of good, bad, and total cholesterol and triglycerides to assess cardiovascular risk.',
    'நல்ல மற்றும் கெட்ட கொழுப்புகள் மற்றும் ட்ரைகிளிசரைடு அளவுகளை அளவிடுவதன் மூலம் இதய இரத்தக் குழாய் ஆரோக்கியத்தை விரிவாக மதிப்பிடுகிறது.',
    '["Total Cholesterol", "HDL (Good Cholesterol)", "LDL (Bad Cholesterol)", "VLDL Cholesterol", "Serum Triglycerides", "TC / HDL Ratio & Atherogenic Index"]'::jsonb,
    '["மொத்த சீரம் கொலஸ்ட்ரால்", "HDL (நல்ல கொலஸ்ட்ரால்)", "LDL (கெட்ட கொலஸ்ட்ரால்)", "VLDL கொலஸ்ட்ரால்", "சீரம் ட்ரைகிளிசரைடுகள்", "TC/HDL விகிதம் & இதய அபாயக் காரணி"]'::jsonb,
    'Strict 10-12 hours overnight fasting mandatory. Plain water permitted.',
    'கட்டாயம் 10 முதல் 12 மணி நேரம் இரவு வெறும் வயிறு தேவை. தண்ணீர் மட்டும் குடிக்கலாம்.',
    '3 ml Venous Blood (Serum Separator)',
    '3 மிலி சிரை இரத்தம் (சீரம்)',
    'Same Day Evening (Within 6 Hours)',
    'அன்றே அறிக்கை (6 மணி நேரத்திற்குள்)',
    'Critical screening tool for coronary artery disease, atherosclerosis, hypertension, and stroke risk stratification.',
    'மாரடைப்பு, இரத்தக் குழாய் அடைப்பு மற்றும் பக்கவாதம் ஏற்படும் அபாயத்தை முன்கூட்டியே எச்சரிக்கும்.',
    'Same Day Report',
    'அன்றே அறிக்கை வழங்கப்படும்',
    'Fasting: 12 Hrs',
    'வெறும் வயிறு: 12 மணி நேரம்',
    'heart',
    550.00
),
(
    'sugar',
    'Blood Sugar Evaluation (FBS, PPBS & HbA1c)',
    'இரத்த சர்க்கரை அளவு பரிசோதனை (FBS, PPBS & HbA1c)',
    'Blood & Pathology',
    'இரத்தம் & நோயியல்',
    '/assets/images/tests/test-sugar-analyzer.png',
    'Gold-standard glycemic control battery diagnosing prediabetes, diabetes, and reflecting 90-day average blood glucose levels.',
    'சர்க்கரை நோய் கண்டறிதல், சிகிச்சை மற்றும் கடந்த 3 மாத கால இரத்த சர்க்கரை கட்டுப்பாட்டைத் துல்லியமாக அறியும் கோல்ட் ஸ்டாண்டர்ட் பரிசோதனை.',
    '["Fasting Blood Sugar (FBS)", "Post-Prandial Blood Sugar (PPBS)", "Random Blood Sugar (RBS)", "Glycated Hemoglobin (HbA1c)", "Estimated Average Glucose (eAG)"]'::jsonb,
    '["வெறும் வயிற்று சர்க்கரை (FBS)", "உணவுக்குப் பின் 2 மணி நேர சர்க்கரை (PPBS)", "ரேண்டம் சர்க்கரை (RBS)", "HbA1c (3 மாத சராசரி சர்க்கரை அளவு)", "சராசரி இரத்த குளுக்கோஸ் மதிப்பீடு"]'::jsonb,
    'FBS: 8-10 hours fasting. PPBS: exactly 2 hours after commencing your regular breakfast.',
    'FBS: 8-10 மணி நேரம் வெறும் வயிறு. PPBS: காலை உணவு முடிந்து சரியாக 2 மணி நேரத்தில் மாதிரி கொடுக்க வேண்டும்.',
    'Fluoride oxalate & EDTA tubes',
    'புளோரைடு / EDTA இரத்த குப்பிகள்',
    '2 to 3 Hours (Rapid Reporting)',
    '2 முதல் 3 மணி நேரம் (விரைவு அறிக்கை)',
    'Imperative for continuous diabetes management, therapy titration, and microvascular complication prevention.',
    'ப்ரீ-டயாபடீஸ் மற்றும் டைப் 1, டைப் 2 சர்க்கரை நோயை முறையாகக் கண்காணிக்க அவசியமானது.',
    'Turnaround: 2-3 Hours',
    'முடிவு வழங்கும் நேரம்: 2-3 மணி நேரம்',
    'Fasting & Post-Meal',
    'வெறும் வயிறு & உணவுக்குப் பின்',
    'sugar',
    450.00
),
(
    'thyroid',
    'Thyroid Profile (Total T3, Total T4, Ultrasensitive TSH)',
    'தைராய்டு பரிசோதனை (T3, T4, TSH)',
    'Organ Profiles',
    'உறுப்பு செயல்பாட்டுப் பரிசோதனைகள்',
    '/assets/images/tests/test-thyroid-pipettes.png',
    'Measures primary endocrine hormones orchestrating basal metabolic rate, body temperature, cardiovascular rhythm, and energy expenditure.',
    'உடலின் வளர்சிதை மாற்றம், வெப்பநிலை, ஆற்றல் மற்றும் இதயத் துடிப்பைக் கட்டுப்படுத்தும் முக்கிய நாளமில்லா ஹார்மோன்களை அளவிடுகிறது.',
    '["Total Triiodothyronine (T3)", "Total Thyroxine (T4)", "Ultrasensitive Thyroid Stimulating Hormone (TSH)", "Free T3 / Free T4 (upon clinical indication)"]'::jsonb,
    '["மொத்த ட்ரையோடோதைரோனைன் (T3)", "மொத்த தைராக்சின் (T4)", "அதிஉணர்திறன் TSH (தைராய்டு தூண்டும் ஹார்மோன்)", "Free T3 / Free T4 (மருத்துவர் பரிந்துரைப்படி)"]'::jsonb,
    'Early morning draw recommended. Ingest prescribed thyroid replacement tablets only after sample withdrawal.',
    'காலை நேர மாதிரி மிகவும் சிறந்தது. தைராய்டு மாத்திரைகளை இரத்த மாதிரி கொடுத்த பின்னரே உட்கொள்ள வேண்டும்.',
    '3 ml Venous Blood (Clot Activator)',
    '3 மிலி சிரை இரத்தம் (சீரம்)',
    'Same Day Evening',
    'அன்றே மாலை அறிக்கை',
    'Diagnoses hypothyroidism, hyperthyroidism, subclinical thyroiditis, unexplained weight anomalies, and fatigue.',
    'ஹைப்போதைராய்டிசம், ஹைப்பர்தைராய்டிசம், காரணமற்ற எடை மாற்றம் மற்றும் உடல் சோர்வைக் கண்டறியும்.',
    'Same Day Evening',
    'அன்றே மாலை அறிக்கை',
    'Morning Fasting Preferred',
    'காலை வெறும் வயிறு சிறந்தது',
    'thyroid',
    500.00
),
(
    'urine-stool',
    'Urine & Stool Routine & Microscopy Examination',
    'சிறுநீர் & மலம் வழக்கமான மற்றும் நுண்ணோக்கி பரிசோதனை',
    'Blood & Pathology',
    'இரத்தம் & நோயியல்',
    '/assets/images/tests/test-urine-bench.png',
    'Comprehensive macroscopic, chemical, and microscopic examination screening renal filtration and gastrointestinal function.',
    'சிறுநீரகக் கோளாறுகள், சிறுநீர்ப் பாதை நோய்த்தொற்றுகள் (UTI) மற்றும் இரைப்பை குடல் ஆரோக்கியத்தை அறியும் நுண்ணோக்கி ஆய்வு.',
    '["Physical (Color, Appearance, Specific Gravity)", "Chemical (pH, Protein, Sugar, Ketones, Bilirubin, Blood)", "Microscopic (Pus Cells, RBCs, Epithelial Cells, Crystals, Casts, Bacteria)", "Stool: Occult Blood, Ova, Cysts, Parasites"]'::jsonb,
    '["இயற்பியல் ஆய்வு (நிறம், தோற்றம், அடர்த்தி)", "வேதியியல் ஆய்வு (pH, புரதம், குளுக்கோஸ், கீட்டோன்கள், இரத்தம்)", "நுண்ணோக்கி ஆய்வு (சீழ் செல்கள், RBC, எபிதீலியல் செல்கள், பாக்டீரியா)", "மலம்: மறைமுக இரத்தம், ஒட்டுண்ணிகள், முட்டைகள்"]'::jsonb,
    'Clean-catch midstream morning sample into the sterile container supplied by Sri Durgaa Lab.',
    'காலை முதல் சிறுநீரை சுத்தமான கன்டெய்னரில் சேகரிக்க வேண்டும். மாதிரி குப்பி ஆய்வகத்தில் வழங்கப்படும்.',
    'Sterile Specimen Container',
    'சுத்தமான மலட்டு சிறுநீர் / மலம் குப்பி',
    '3 to 5 Hours',
    '3 முதல் 5 மணி நேரம்',
    'Screens urinary tract infections (UTI), glomerulonephritis, nephrolithiasis, and intestinal parasitic burdens.',
    'அறிகுறியற்ற சிறுநீர்த் தொற்று, சிறுநீரகக் கற்கள் மற்றும் குடல் புழுக்களைக் கண்டறிய உதவுகிறது.',
    'Turnaround: 3-5 Hours',
    'முடிவு வழங்கும் நேரம்: 3-5 மணி நேரம்',
    'Morning Clean Catch',
    'காலை தூய மாதிரி சிறந்தது',
    'flask',
    150.00
),
(
    'ecg',
    'ECG – 12-Lead Resting Electrocardiogram',
    'ECG – 12-Lead இதய மின் துடிப்புப் பரிசோதனை',
    'Cardiology & Radiology',
    'இதயம் & ஸ்கேன்/எக்ஸ்-ரே',
    '/assets/images/tests/test-ecg-machine.png',
    'Records instantaneous cardiac electrical vectors across 12 standard anatomical leads to diagnose conduction defects.',
    'இதயத் தசைகளின் மின் சமிக்ஞைகள் மற்றும் இதயத் துடிப்பின் சீரான இயக்கத்தைப் பதிவு செய்யும் பாதுகாப்பான பரிசோதனை.',
    '["Heart Rate & Rhythm Dynamics", "P-Wave, PR-Interval, QRS-Duration", "ST-Segment & T-Wave Morphology", "Ischemia & Myocardial Infarction Patterns", "Arrhythmia Detection & Conduction Blocks"]'::jsonb,
    '["இதயத் துடிப்பு & ரிதம் பகுப்பாய்வு", "P அலை, PR இடைவெளி, QRS காம்ப்ளக்ஸ்", "ST பிரிவு & T அலை மதிப்பீடு", "இரத்த ஓட்டக் குறைவு & மாரடைப்பு மாற்றங்கள்", "துடிப்பு ஒழுங்கின்மை (Arrhythmia) கண்டறிதல்"]'::jsonb,
    'Wear loose comfortable two-piece clothing. Rest quietly for 10 minutes prior to procedure.',
    'வசதியான இருபகுதி ஆடைகளை அணியவும். பரிசோதனைக்கு 10 நிமிடங்களுக்கு முன் அமைதியாக ஓய்வெடுக்கவும்.',
    'Direct in-clinic procedural test (10 Minutes)',
    'மையத்தில் நேரடி மருத்துவப் பரிசோதனை (10 நிமிடம்)',
    'Immediate Trace & Verified Cardiologist Impression',
    'உடனடி அறிக்கை & மருத்துவர் சரிபார்ப்பு',
    'First-line emergency triage for chest pain, palpitations, syncope, breathlessness, and pre-anesthetic screening.',
    'நெஞ்சு வலி, படபடப்பு, மூச்சுத் திணறல் மற்றும் மயக்கம் ஏற்படும் போது உடனடியாகச் செய்ய வேண்டிய சோதனை.',
    'Immediate Report',
    'உடனடி அறிக்கை',
    'No Fasting Needed',
    'வெறும் வயிறு: தேவையில்லை',
    'ecg',
    300.00
),
(
    'xray',
    'Digital X-Ray (High-Resolution Radiography)',
    'டிஜிட்டல் எக்ஸ்-ரே (High-Resolution Radiography)',
    'Cardiology & Radiology',
    'இதயம் & ஸ்கேன்/எக்ஸ்-ரே',
    '/assets/images/tests/test-xray-focused.png',
    'Low-radiation digital radiography capturing high-contrast structural views of the thorax, skeleton, and articulation joints.',
    'குறைந்த கதிர்வீச்சு டிஜிட்டல் டிடெக்டர்களைப் பயன்படுத்தி எலும்பு கட்டமைப்பு, நுரையீரல் மற்றும் மூட்டுகளைத் தெளிவாகப் படம்பிடிக்கும் முறை.',
    '["Chest PA / AP Radiograph", "Trauma & Fracture Screening", "Cervical, Thoracic & Lumbar Spine Views", "Joint Evaluation & Degenerative Changes", "Plain Abdominal KUB Radiography"]'::jsonb,
    '["மார்பு எக்ஸ்-ரே (Chest PA / AP Views)", "எலும்பு முறிவு பரிசோதனை (Fracture Screen)", "முதுகெலும்பு எக்ஸ்-ரே (கழுத்து, முதுகு, இடுப்பு)", "மூட்டு & தேய்மான மதிப்பீடு", "வயிற்றுப் பகுதி எக்ஸ்-ரே"]'::jsonb,
    'Remove metallic jewelry, pendants, piercings, or clothing with metal buttons in the examination region.',
    'பரிசோதனை செய்யப்படும் பகுதியில் உள்ள உலோக நகைகள் அல்லது ஜிப் உள்ள ஆடைகளை அகற்றவும்.',
    'Direct in-clinic radiographic acquisition (5-10 Minutes)',
    'மையத்தில் நேரடி கதிரியக்கப் பரிசோதனை (5-10 நிமிடம்)',
    'Processed Film & Diagnostic Report within 30-45 Mins',
    'பிலிம் மற்றும் அறிக்கை 30-45 நிமிடங்களில்',
    'Ultralow patient radiation dose with high spatial resolution and verified radiologist differential reports.',
    'குறைந்த கதிர்வீச்சுடன் உடனடி துல்லியமான படம் மற்றும் சான்றிதழ் பெற்ற ரேடியாலஜிஸ்ட் சரிபார்ப்பு.',
    '30-45 Mins Report',
    '30-45 Mins Report',
    'Low Radiation Dose',
    'Low Radiation Dose',
    'xray',
    350.00
),
(
    'hiv',
    'HIV 1 & 2 Antibody / Antigen Screen (4th Gen ECLIA)',
    'HIV 1 & 2 ஆன்டிபாடி / ஆன்டிஜென் ஸ்கிரீன்',
    'Specialized Assays',
    'சிறப்பு பரிசோதனைகள்',
    '/assets/images/tests/test-hiv-station.png',
    'High-specificity 4th generation chemiluminescent assay detecting both Human Immunodeficiency Virus antibodies and p24 antigen.',
    'முழுமையான ரகசியத்தன்மையுடன் HIV ஆன்டிபாடிகள் மற்றும் வைரஸ் ஆன்டிஜென்களைக் கண்டறியும் உயர் உணர்திறன் கொண்ட ஆய்வு.',
    '["HIV-1 Specific Antibodies", "HIV-2 Specific Antibodies", "p24 Viral Capsid Antigen (4th Gen Duo)", "Strict Anonymity & Code-Secured Delivery"]'::jsonb,
    '["HIV-1 ஆன்டிபாடிகள் கண்டறிதல்", "HIV-2 ஆன்டிபாடிகள் கண்டறிதல்", "P24 ஆன்டிஜென் கண்டறிதல் (4th Gen Duo Immunoassay)", "100% நோயாளி ரகசியப் பாதுகாப்பு உறுதி"]'::jsonb,
    'No fasting needed. Pre-test and post-test counseling available with absolute medical confidentiality.',
    'உணவுக் கட்டுப்பாடு தேவையில்லை. பரிசோதனைக்கு முந்தைய மற்றும் பிந்தைய ரகசிய ஆலோசனை உண்டு.',
    '3 ml Venous Blood (Serum)',
    '3 மிலி சிரை இரத்தம் (சீரம்)',
    '4 to 6 Hours (Sealed Confidential Report)',
    '4 முதல் 6 மணி நேரம் (பாதுகாப்பான ரகசிய அறிக்கை)',
    'Processed under stringent WHO and NACO laboratory protocols with zero third-party disclosure guarantee.',
    'WHO & NACO ஆய்வக நெறிமுறைகளின்படி முழுமையான தனியுரிமையுடன் செய்யப்படுகிறது.',
    'Turnaround: 4-6 Hours',
    'Turnaround: 4-6 Hours',
    '100% Confidential',
    '100% Confidential',
    'shield',
    400.00
),
(
    'pregnancy',
    'Pregnancy Screen (Beta-hCG Rapid & Quantitative Serum)',
    'கர்ப்பப் பரிசோதனை (Beta-hCG சிறுநீர் & இரத்தம்)',
    'Specialized Assays',
    'சிறப்பு பரிசோதனைகள்',
    '/assets/images/tests/test-pregnancy-station.png',
    'Ultra-sensitive quantitative serum assay and rapid immunochromatographic urine screen measuring human Chorionic Gonadotropin.',
    'சிறுநீர் அல்லது இரத்தத்தில் மனித கோரியானிக் கோனாடோட்ரோபின் (hCG) ஹார்மோனைக் கண்டறியும் நம்பகமான சோதனை.',
    '["Urine Beta-hCG (Rapid High-Sensitivity Screen)", "Serum Beta-hCG (Quantitative Blood Assay)", "Gestational Age Estimation Correlation", "Early Pregnancy Confirmation"]'::jsonb,
    '["சிறுநீர் Beta-hCG (உடனடி உயர் உணர்திறன் சோதனை)", "சீரம் Beta-hCG (துல்லியமான இரத்த அளவு ஆய்வு)", "கருவுற்ற கால அளவு மதிப்பீடு", "ஆரம்ப கர்ப்ப உறுதிப்படுத்தல்"]'::jsonb,
    'For urine: First morning void is best. For blood: No fasting required.',
    'சிறுநீருக்கு: காலை முதல் சிறுநீர் சிறந்தது. இரத்தத்திற்கு: வெறும் வயிறு தேவையில்லை.',
    'Sterile Morning Urine or 2 ml Blood Serum',
    'மலட்டு காலை சிறுநீர் அல்லது 2 மிலி இரத்த சீரம்',
    'Rapid: Urine in 30 Mins | Serum in 3 Hours',
    'சிறுநீர்: 30 நிமிடம் | இரத்தம்: 3 மணி நேரம்',
    'Confirms early pregnancy, tracks healthy gestational hormone doubling, and evaluates ectopic risks.',
    'ஆரம்பகால கருவுறுதலை உறுதிப்படுத்தவும் ஆரோக்கியமான ஹார்மோன் இரட்டிப்பை கண்காணிக்கவும் உதவுகிறது.',
    'Rapid Report: 30 Mins',
    'Rapid Report: 30 Mins',
    'Morning Sample Best',
    'Morning Sample Best',
    'baby',
    300.00
)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    title_ta = EXCLUDED.title_ta,
    category = EXCLUDED.category,
    category_ta = EXCLUDED.category_ta,
    price = EXCLUDED.price;

-- Seed Health Packages
INSERT INTO health_packages (
    id, name, name_ta, badge, badge_ta, summary, summary_ta,
    features, features_ta, note, note_ta, is_popular, price
) VALUES
(
    'basic-health',
    'Basic Health Checkup',
    'அடிப்படை உடல் பரிசோதனை',
    'Essential Screening',
    'அத்தியாவசிய பரிசோதனை',
    'Covers fundamental blood cell counts, vital organ sugar baseline, and routine excretory screening.',
    'இரத்த அணுக்கள், சர்க்கரை மற்றும் அடிப்படை உடல் இயக்கங்களை மதிப்பீடு செய்யும் அத்தியாவசிய தொகுப்பு.',
    '["Complete Blood Count (CBC)", "Fasting Blood Sugar (FBS)", "Urine Routine & Microscopy", "Blood Pressure & BMI Check", "Post-Test Guidance Summary"]'::jsonb,
    '["முழு இரத்த அணுக்கள் (CBC)", "வெறும் வயிற்று சர்க்கரை (FBS)", "சிறுநீர் வழக்கமான ஆய்வு", "இரத்த அழுத்தம் & BMI ஆய்வு", "ஆய்வக வழிகாட்டல் ஆலோசனை"]'::jsonb,
    'Ideal for young adults, college fitness certificates, or preliminary work-entry medical checkups.',
    'இளைஞர்கள், கல்லூரி மற்றும் வேலைவாய்ப்பு உடற்தகுதிச் சான்றிதழுக்கு ஏற்றது.',
    FALSE,
    499.00
),
(
    'complete-health',
    'Complete Health Checkup',
    'முழு உடல் நல்வாழ்வு பரிசோதனை',
    'Most Popular • Recommended',
    'மிகவும் பிரபலமானது • பரிந்துரைக்கப்படுவது',
    'Our flagship comprehensive preventive battery checking heart, kidney, liver, metabolism, and lipid risk.',
    'இதயம், கல்லீரல், சிறுநீரகங்கள், கொலஸ்ட்ரால் மற்றும் வளர்சிதை மாற்றத்தை முழுமையாக அறியும் முழு உடல் தொகுப்பு.',
    '["Complete Hemogram (CBC + ESR)", "Kidney Function Test (KFT / Renal Profile)", "Liver Function Test (LFT / Hepatic Profile)", "Fasting Lipid Profile (Cardiovascular Risk)", "Fasting & Post-Prandial Glucose / HbA1c", "12-Lead Resting ECG", "Urine Routine Complete Analysis", "Free Home Sample Collection Included"]'::jsonb,
    '["முழு இரத்த அணுக்கள் (CBC + ESR)", "சிறுநீரக செயல்பாட்டு பரிசோதனை (KFT)", "கல்லீரல் செயல்பாட்டு பரிசோதனை (LFT)", "முழு கொலஸ்ட்ரால் பரிசோதனை (Lipid Profile)", "சர்க்கரை & HbA1c (3 மாத சராசரி)", "12-Lead இதய மின் துடிப்பு (ECG)", "சிறுநீர் முழுமையான பரிசோதனை", "இலவச வீட்டிற்கே வந்து மாதிரி எடுத்தல்"]'::jsonb,
    'Recommended for adults aged 30+ once every 6 to 12 months for proactive preventive health.',
    '30 வயதிற்கு மேற்பட்டவர்கள் 6 முதல் 12 மாதங்களுக்கு ஒருமுறை எடுக்க வேண்டிய முழுமையான பரிசோதனை.',
    TRUE,
    1499.00
),
(
    'advanced-health',
    'Advanced Health Checkup',
    'மேம்பட்ட முழு உடல் பரிசோதனை',
    'Full Diagnostic Battery',
    'முழுமையான மருத்துவத் தொகுப்பு',
    'Exhaustive executive screening combining all core profiles with digital imaging and thyroid hormonal assays.',
    'அனைத்து முதன்மை உறுப்பு பரிசோதனைகளுடன் டிஜிட்டல் எக்ஸ்-ரே மற்றும் தைராய்டு ஹார்மோன் அடங்கிய மேம்பட்ட தொகுப்பு.',
    '["All 8 diagnostic profiles from Complete Health Checkup", "Complete Thyroid Profile (T3, T4, Ultrasensitive TSH)", "High-Resolution Digital Chest X-Ray (PA View)", "Serum Electrolytes (Sodium, Potassium, Chloride)", "Serum Uric Acid & Cardiac Atherogenic Index", "Same-Day Priority Digital Reporting to WhatsApp", "Free Home Sample Collection & Follow-up Support"]'::jsonb,
    '["முழு உடல் பரிசோதனையின் அனைத்து 8 அம்சங்களும்", "முழு தைராய்டு பரிசோதனை (T3, T4, TSH)", "டிஜிட்டல் மார்பு எக்ஸ்-ரே (High-Res Digital X-Ray)", "சீரம் எலக்ட்ரோலைட்டுகள் (Na, K, Cl)", "யூரிக் அமிலம் & இதய ஆபத்துக் குறியீடு", "அன்றே வாட்ஸ்அப்பில் முன்னுரிமை அறிக்கை", "இலவச வீட்டிற்கே மாதிரி எடுத்தல் & ஆதரவு"]'::jsonb,
    'Designed for senior citizens, executive corporate screenings, and individuals with family chronic history.',
    'முதியவர்கள், தீவிர உடல்நலக் கண்காணிப்பு தேவைப்படுவோர் மற்றும் கார்ப்பரேட் ஊழியர்களுக்கு ஏற்றது.',
    FALSE,
    2499.00
)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    name_ta = EXCLUDED.name_ta,
    price = EXCLUDED.price;

-- Seed Patient Reviews
INSERT INTO reviews (
    review_code, patient_name, location, rating, test_en, test_ta,
    category, date_text_en, date_text_ta, initials, avatar_gradient,
    verified, comment_en, comment_ta, is_approved
) VALUES
(
    'rev-1',
    'S. Ravichandran',
    'Ponneri Bazaar',
    5,
    'Home Blood Collection – Sugar & CBC',
    'வீட்டிற்கே வந்து மாதிரி எடுத்தல் – சர்க்கரை & CBC',
    'home',
    '2 days ago',
    '2 நாட்களுக்கு முன்',
    'SR',
    'linear-gradient(135deg, #1264D8, #18B6D9)',
    TRUE,
    'My 78-year-old mother needed regular fasting sugar and CBC tests. The technician arrived right on time at 7:15 AM at our house in Ponneri Bazaar. Needle prick was completely painless, and reports were sent to my WhatsApp by afternoon. Exceptional service!',
    'என் 78 வயது தாயாருக்கு வீட்டிற்கே வந்து வெறும் வயிற்று சர்க்கரை மற்றும் CBC மாதிரி எடுத்தார்கள். அதிகாலை 7:15 மணிக்கு சரியான நேரத்திற்கு வந்து வலி இல்லாமல் ரத்தம் எடுத்தார் ஆய்வக ஊழியர். மதியமே வாட்ஸ்அப்பில் ரிப்போர்ட் வந்துவிட்டது. மிகச் சிறந்த சேவை!',
    TRUE
),
(
    'rev-2',
    'Priya Venkatesan',
    'NGO Colony, Ponneri',
    5,
    'Complete Health Checkup Package',
    'முழு உடல் நல்வாழ்வு பரிசோதனை',
    'packages',
    '5 days ago',
    '5 நாட்களுக்கு முன்',
    'PV',
    'linear-gradient(135deg, #8b5cf6, #ec4899)',
    TRUE,
    'Took the Complete Health Checkup package including LFT, KFT, Lipid profile, and ECG. The clinic is spotless, well-sanitized, and the staff are courteous. Rates are very reasonable compared to Chennai city hospitals. 25 years of trust is well deserved!',
    'முழு உடல் பரிசோதனை தொகுப்பில் கல்லீரல், சிறுநீரக பரிசோதனை மற்றும் ECG எடுத்தேன். லேப் மிகவும் சுத்தமாகவும் ஊழியர்கள் கனிவாகவும் இருந்தனர். சென்னை மருத்துவமனைகளை விட மிகக் குறைவான கட்டணம். 25 வருட நம்பிக்கை உண்மையானது!',
    TRUE
),
(
    'rev-3',
    'Dr. M. Jayakumar',
    'Consultant Physician, Ponneri',
    5,
    'Thyroid & Hormone Assays',
    'தைராய்டு மற்றும் ஹார்மோன் பரிசோதனைகள்',
    'accuracy',
    '1 week ago',
    '1 வாரத்திற்கு முன்',
    'MJ',
    'linear-gradient(135deg, #059669, #10b981)',
    TRUE,
    'As a practicing physician in Ponneri, I have been recommending Sri Durgaa Lab to my patients for over 15 years. Their biochemistry analyzer calibration and hematology accuracy are gold standard. Fast and reliable emergency turnaround.',
    'பொன்னேரியில் மருத்துவராக பணியாற்றும் நான் 15 ஆண்டுகளுக்கும் மேலாக நோயாளிகளுக்கு ஸ்ரீ துர்கா லேப்பை பரிந்துரைக்கிறேன். அவர்களின் பரிசோதனை துல்லியம் மற்றும் விரைவான அறிக்கைகள் மிகவும் நம்பகமானவை.',
    TRUE
),
(
    'rev-4',
    'K. Subramanian',
    'Anna Nagar, Ponneri',
    5,
    '12-Lead ECG & Digital X-Ray',
    '12-Lead ECG மற்றும் டிஜிட்டல் எக்ஸ்-ரே',
    'accuracy',
    '1 week ago',
    '1 வாரத்திற்கு முன்',
    'KS',
    'linear-gradient(135deg, #f59e0b, #ef4444)',
    TRUE,
    'Had sudden chest discomfort and visited Durga Lab for emergency ECG and chest X-ray. They attended immediately without any waiting time. Verified cardiologist report was ready in 25 minutes. Very reassuring care in critical moments.',
    'திடீர் நெஞ்சு பாரத்திற்காக அவசர ECG மற்றும் டிஜிட்டல் எக்ஸ்-ரே எடுக்க சென்றேன். காத்திருக்க வைக்காமல் உடனே பரிசோதனை செய்தனர். 25 நிமிடங்களில் மருத்துவர் சரிபார்த்த அறிக்கை கிடைத்தது. பயனுள்ள அவசர சேவை.',
    TRUE
),
(
    'rev-5',
    'Anitha Murugan',
    'Minjur',
    5,
    'Pregnancy & Beta-hCG Screen',
    'கர்ப்பப் பரிசோதனை (Beta-hCG)',
    'accuracy',
    '2 weeks ago',
    '2 வாரங்களுக்கு முன்',
    'AM',
    'linear-gradient(135deg, #ec4899, #f43f5e)',
    TRUE,
    'Came all the way from Minjur after hearing high recommendations. The staff treated me with so much care and dignity. The Beta-hCG blood test report was delivered within 3 hours on WhatsApp. Highly hygienic environment!',
    'மீஞ்சூரில் இருந்து சிறந்த பரிந்துரையின் பேரில் வந்தேன். ஊழியர்கள் மிகவும் பரிவுடன் கவனித்தனர். 3 மணி நேரத்திற்குள் கர்ப்பப் பரிசோதனை அறிக்கை வாட்ஸ்அப்பில் கிடைத்தது. மிகத் தூய்மையான ஆய்வகம்!',
    TRUE
)
ON CONFLICT (review_code) DO NOTHING;

-- Seed Clinic Settings
INSERT INTO lab_settings (setting_key, setting_value, description) VALUES
('clinic_profile', '{
    "name": "Sri Durgaa Clinical Laboratory",
    "name_ta": "ஸ்ரீ துர்கா கிளினிக்கல் லேபரேட்டரி",
    "established": 1999,
    "experience_years": 25,
    "phones": ["+91 98436 96625", "+91 87783 17824"],
    "whatsapp": "919843696625",
    "address_en": "No. 12, Bazaar Street, Opposite Taluk Hospital, Ponneri - 601 204",
    "address_ta": "எண் 12, பஜார் வீதி, தாலுகா அரசு மருத்துவமனை எதிரில், பொன்னேரி - 601 204",
    "hours_en": "Mon - Sat: 07:00 AM - 09:00 PM | Sun: 07:00 AM - 01:00 PM",
    "home_collection_radius_km": 15
}'::jsonb, 'Core laboratory branding and contact parameters')
ON CONFLICT (setting_key) DO UPDATE SET setting_value = EXCLUDED.setting_value;
